name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/deploy.yml'
      - '.github/workflows/scheduled-tasks.yml'
      - '.github/workflows/**.md'
      
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint || echo "Linting skipped"

      - name: Run tests
        run: npm test || echo "No test scripts found"
