name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Continuous Integration (CI) workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      # Removed build step (for backend projects)
      - name: Deploy to Server
        run: |
          echo "🚀 Deployment process starts here"
