name: Scheduled Tasks

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 2 AM UTC

jobs:   #jobs hjkjj
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cleanup script
        run: echo "Running daily maintenance tasks..."
